### ISSUE TITLE
有咩有 vue2的啊 或者推荐个有这种导航栏切换功能的项目

### ISSUE THREAD

**Issue by Bubbfish** [wuufeii/vue3-admin-vite#5]

**Comment by wuufeii** [comment]
iview的： https://github.com/iview/iview-admin

elementUI的：https://github.com/loveRandy/vue-cli3.0-vueadmin

**Comment by Bubbfish** [comment]
> iview的： https://github.com/iview/iview-admin
> 
> elementUI的：https://github.com/loveRandy/vue-cli3.0-vueadmin

没有你的导航栏切换功能呀，目前最需要这个功能。有没有带 导航栏切换的

**Comment by wuufeii** [comment]
你是说菜单栏切换成左侧和上面这种吗？

**Comment by Bubbfish** [comment]
> 

是的

**Comment by wuufeii** [comment]
那这个是你需要的：https://github.com/ant-design/ant-design-pro

**Comment by Bubbfish** [comment]
> 那这个是你需要的：https://github.com/ant-design/ant-design-pro

麻烦你了。。我就是想要用vue2 和 elementui 和 js的。。你有见过没，，没有就算了，，太麻烦你了 很不好意思！！！！！！！！主要我现在没时间，否则我用你这个项目自己对着慢慢写成vue2也可以，，所以现在就很需要一个满足我的脚手架。。

**Comment by wuufeii** [comment]
好吧，那你找找吧，网上肯定是有的。

**Comment by Bubbfish** [comment]
> 好吧，那你找找吧，网上肯定是有的。

ok 谢了
